import assert from 'node:assert/strict';
import { buildPrompt, includedIdeas, descendants, escapeHTML, activeIdeas, scopedIdeas, questionGroups, deletionPlan, deleteIdeas, restoreIdeas, importExamples, STARTERS } from './public/core.mjs';
const topic = { id: 't', title: '主题', template: 'general', constraints: '保留已有设定', deletedAt: null };
const idea = (id, parentId = null) => ({ id, topicId: 't', parentId, title: id, body: `原始内容 ${id}`, kind: 'idea', status: 'spark', source: '', tags: [], createdAt: '2026-01-01', updatedAt: '2026-01-01', deletedAt: null });
const workspace = { topics: [topic], ideas: [idea('a'), idea('b', 'a'), idea('c'), idea('d', 'b')] };
assert.deepEqual(includedIdeas(workspace, 't', ['d']).items.map(i => i.id), ['a', 'b', 'd']);
assert.equal(includedIdeas(workspace, 't', ['d']).contextual, 2);
assert.deepEqual([...descendants(workspace.ideas, 'a')], ['a', 'b', 'd']);
const prompt = buildPrompt(workspace, 't', { selectedIds: ['d'] });
assert.ok(prompt.includes('保留已有设定') && prompt.includes('另有 1 条未选入') && prompt.includes('上级背景'));
assert.ok(prompt.includes('此轮以梳理为目标') && !prompt.includes('原始内容 c'));
assert.ok(buildPrompt(workspace, 't', { mode: 'execute' }).includes('可直接使用的结果'));
assert.equal(escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;');
assert.equal(activeIdeas({ ...workspace, topics: [{ ...topic, deletedAt: '2026-01-01' }] }).length, 0);
assert.deepEqual(scopedIdeas(workspace, ['a'], true).map(i => i.id), ['a', 'b', 'd']);
assert.deepEqual(scopedIdeas(workspace, ['a'], false).map(i => i.id), ['a']);
assert.deepEqual(scopedIdeas(workspace, [], true), []);
assert.deepEqual(questionGroups(workspace.ideas).map(group => [group.root.id, group.items.map(item => item.idea.id)]), [['a', ['a', 'b', 'd']], ['c', ['c']]]);
const searchGroups = questionGroups(workspace.ideas, [workspace.ideas[3]]);
assert.deepEqual(searchGroups[0].items.map(item => [item.idea.id, item.depth, item.contextual]), [['a', 0, true], ['b', 1, true], ['d', 2, false]]);
assert.equal(searchGroups[0].total, 3);
const snapshot = JSON.stringify(workspace);
const preview = deletionPlan(workspace, ['a', 'b'], 'subtree');
assert.equal(preview.ids.size, 3); assert.equal(preview.selected, 2);
assert.equal(JSON.stringify(workspace), snapshot);
const preserve = structuredClone(workspace);
assert.deepEqual(deleteIdeas(preserve, ['b'], 'selected', 'deleted-1'), { deleted: 1, preserved: 1, promoted: 1 });
assert.equal(preserve.ideas.find(i => i.id === 'd').parentId, 'a');
assert.equal(preserve.ideas.find(i => i.id === 'd').body, '原始内容 d');
const preserveRoot = structuredClone(workspace);
deleteIdeas(preserveRoot, ['a', 'b'], 'selected', 'deleted-2');
assert.equal(preserveRoot.ideas.find(i => i.id === 'd').parentId, null);
assert.equal(activeIdeas(preserveRoot).length, 2);
const concurrent = structuredClone(workspace);
concurrent.ideas.find(i => i.id === 'd').parentId = null; // Another device separated this branch before CAS rebase.
concurrent.ideas.push(idea('new-child', 'b'));
deleteIdeas(concurrent, ['a'], 'subtree', 'deleted-3');
assert.equal(concurrent.ideas.find(i => i.id === 'd').deletedAt, null);
assert.equal(concurrent.ideas.find(i => i.id === 'new-child').deletedAt, 'deleted-3');
const recycle = structuredClone(workspace);
recycle.ideas.find(i => i.id === 'd').deletedAt = 'older-batch';
deleteIdeas(recycle, ['a'], 'subtree', 'newer-batch');
assert.equal(restoreIdeas(recycle, 'a', 'restored'), 2);
assert.equal(recycle.ideas.find(i => i.id === 'd').deletedAt, 'older-batch');
recycle.ideas.find(i => i.id === 'a').deletedAt = 'root-batch';
recycle.ideas.find(i => i.id === 'b').deletedAt = 'parent-batch';
assert.equal(restoreIdeas(recycle, 'd', 'restored-child'), 3);
assert.ok(recycle.ideas.every(i => !i.deletedAt));
const existing = structuredClone(workspace), seed = { topics: [{ ...topic, id: 'sample' }], ideas: [{ ...idea('sample-root'), topicId: 'sample' }] };
assert.deepEqual(importExamples(existing, seed, ['sample']), ['sample']);
assert.deepEqual(importExamples(existing, seed, ['sample']), []);
existing.topics.find(t => t.id === 'sample').deletedAt = 'user-deleted';
assert.deepEqual(importExamples(existing, seed, ['sample']), []);
assert.equal(existing.topics.find(t => t.id === 'sample').deletedAt, 'user-deleted');
const colliding = { topics: [{ ...topic, id: 'different-sample' }], ideas: [{ ...idea('a'), topicId: 'different-sample' }] };
const beforeCollision = JSON.stringify(existing);
assert.throws(() => importExamples(existing, colliding, ['different-sample']), /冲突/);
assert.equal(JSON.stringify(existing), beforeCollision);
for (const key of ['writing', 'product', 'learning', 'project']) assert.equal(STARTERS[key].storageTemplate, 'general');
const deep = Array.from({ length: 1500 }, (_, index) => idea(`deep-${index}`, index ? `deep-${index - 1}` : null));
assert.equal(questionGroups(deep, [deep.at(-1)])[0].items.length, 1500);
assert.equal(questionGroups(deep, [deep.at(-1)])[0].items.at(-1).depth, 1499);
console.log('core self-check passed: grouped roots/search ancestry, exact AI scope, batch deletion/reparenting/CAS rebase, recovery batches, example isolation, templates, export and escaping');
